{% set version = "0.7.3" %}

package:
  name: pcaspy
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/paulscherrerinstitute/pcaspy
  patches:
    - readline.patch # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - wheel
    - epics-base
    - swig

  run:
    - python

test:
  imports:
    - pcaspy

about:
  home: https://github.com/paulscherrerinstitute/pcaspy
  summary: Portable Channel Access Server in Python
  license: BSD
