init:
  - git config --global core.autocrlf false

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: 3
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3-x64

build: false

install:
  - "%MINICONDA%\\Scripts\\activate.bat"
  - conda config --set always_yes yes --set changeps1 no
  - if defined CONDA_TOKEN (conda config --set anaconda_upload yes) else (set CONDA_TOKEN=token_placeholder)
  - conda config --add channels defaults
  - conda update -q --all
  - conda install conda-build numpy anaconda-client
  - conda info
  # build
  #- "%CMD_IN_ENV% conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing brotli"
  #- "%CMD_IN_ENV% conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing bottle"
  - "%CMD_IN_ENV% conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing epics-base"
  - "%CMD_IN_ENV% conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing pyepics"
  #- "%CMD_IN_ENV% conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing tinydb"
  - "%CMD_IN_ENV% conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing xrt"
  - "%CMD_IN_ENV% conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing bitshuffle"

on_success:
  - echo "Finished building"
