init:
  - git config --global core.autocrlf false

environment:
  matrix:
    - PYTHON_VERSION: 3
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3-x64

build: false

install:
  - "%MINICONDA%\\Scripts\\activate.bat"
  - conda config --set always_yes yes --set changeps1 no
  - if defined CONDA_TOKEN (conda config --set anaconda_upload yes) else (set CONDA_TOKEN=token_placeholder)
  - conda config --add channels defaults
  - conda update -q --all
  - conda install conda-build numpy anaconda-client
  - conda info
  # patch vs2008 express
  - conda install -c conda-forge vs2008_express_vc_python_patch
  - setup_x64
  # build
  - conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing epics-base
  - conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing bitshuffle
  - conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing lzf
  - conda build -c %MY_CONDA_CHANNEL% --token %CONDA_TOKEN% --skip-existing xrayutilities

on_success:
  - echo "Finished building"
