init:
  - git config --global core.autocrlf true

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda-x64

build: false

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda config --add channels defaults
  - conda install conda-build numpy anaconda-client
  - conda info
  # build
  - "%CMD_IN_ENV% conda build -c %CONDA_CHANNEL% --skip-existing brotli"
  - "%CMD_IN_ENV% conda build -c %CONDA_CHANNEL% --skip-existing bottle"
  - "%CMD_IN_ENV% conda build -c %CONDA_CHANNEL% -c conda-forge --skip-existing epics-base"
  - conda search pyparsing
    #- "%CMD_IN_ENV% conda build -c %CONDA_CHANNEL% --skip-existing pyepics"
  - "%CMD_IN_ENV% conda build -c %CONDA_CHANNEL% --skip-existing tinydb"

on_success:
  - if defined CONDA_TOKEN (anaconda -t %CONDA_TOKEN% upload %MINICONDA%\\conda-bld\\win-%PYTHON_ARCH%\\*.tar.bz2)
