python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
c_compiler:
    - vs2008
    - vs2015
    - vs2015
    - vs2015
cxx_compiler:
    - vs2008
    - vs2015
    - vs2015
    - vs2015
zip_keys:
    - python
    - c_compiler
    - cxx_compiler
