package:
  name: cachannel
  version: 3.1.4

source:
  git_rev: 3.1.4
  git_url: https://github.com/CaChannel/CaChannel.git
  patches:
    - readline.patch # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - wheel
    - epics-base
    - enum34 # [py2k]

  run:
    - python
    - enum34 # [py2k]

test:
  imports:
    - CaChannel

  requires:
    - setuptools
    - epics-base
    - numpy
    - enum34 # [py2k]

about:
  home: https://pypi.python.org/pypi/CaChannel
  license: BSD License
  summary: 'CaChannel Interface to EPICS'
