{% set name = "bottle" %}
{% set version = "0.12.18" %}
{% set hash_type = "sha256" %}
{% set hash_value = "0819b74b145a7def225c0e83b16a4d5711fde751cd92bae467a69efce720f69e" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python

test:
  imports:
    - bottle

about:
  home: http://bottlepy.org/
  license: MIT License
  summary: 'Fast and simple WSGI-framework for small web-applications.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
