package:
    name: h5py
    version: 2.7.0alpha

source:
    # path: ..
    git_rev: master
    git_url: https://github.com/h5py/h5py.git

requirements:
  build:
    - python
    - numpy
    - hdf5 ==1.8.17
    - cython
    - six
    - pkgconfig

  run:
    - python
    - numpy
    - hdf5
    - six

about:
    home: https://github.com/h5py/h5py
    summary: "hdf5 library"
