package:
    name: lzf
    version: 0.2.4

source:
    # path: ..
    git_rev: release-0.2.4
    git_url: https://github.com/teepark/python-lzf.git
    patches:
        - hotfix_issue5.diff

requirements:
    host:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python {{ python }}
        - setuptools

    run:
        - python

about:
    home: https://github.com/teepark/python-lzf
    summary: "lzf library"
