package:
    name: lzf
    version: 0.2.4

source:
    fn: python-lzf-0.2.4.tar.gz
    url: https://pypi.io/packages/source/p/python-lzf/python-lzf-0.2.4.tar.gz
    patches:
        - hotfix_issue5.diff

requirements:
    build:
        - m2-gcc-libs # [win]
        - m2-patch # [win]

    host:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python {{ python }}
        - setuptools

    run:
        - python

about:
    home: https://github.com/teepark/python-lzf
    summary: "lzf library"
