{% set version = "3.14.12.8" %}

package:
    name: epics-base
    version: {{ version }}

source:
    fn: baseR{{version}}.tar.gz
    url: https://epics.anl.gov/download/base/baseR{{version}}.tar.gz
    patches:
        - config_site.diff # [not win]
        - config_common.diff # [not win]
        - rules_build.diff
        - config_readline.diff # [linux]

build:
  number: 1
  features:
    - vc9  # [win and py27]
    - vc14 # [win and (py35 or py36)]

requirements:
  build:
    - python # [win]
    - m2w64-make # [win]
    - perl # [win]
    - m2-patch # [win]

about:
    home: https://epics.anl.gov/
    license: Epics Open License
    summary: EPICS Base Library
