{% set version = "3.14.12.8" %}

package:
    name: epics-base
    version: {{ version }}

source:
    fn: baseR{{version}}.tar.gz
    url: https://epics.anl.gov/download/base/baseR{{version}}.tar.gz
    patches:
        - config_site.diff # [not win]
        - config_common.diff # [not win]
        - rules_build.diff # [not win]
        - config_readline.diff # [linux]
        - cas.diff
        - darwin-aarch64.diff
        - linux-aarch64.diff

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python # [win]
    - make # [not win]
    - m2-make # [win]
    - m2-patch # [win]
    - perl # [win]

about:
    home: https://epics.anl.gov/
    license: Epics Open License
    summary: EPICS Base Library
