{% set name = "xrayutilities" %}
{% set version = "1.5.4" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "492632a501d983230c506eeacd9c35166a62fcdd1be792d9eb1bb04f48d3a576" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - setuptools
    - numpy {{ numpy }}
    - scipy
    - h5py

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - h5py

test:
  # Python imports
  imports:
    - xrayutilities
    - xrayutilities.analysis
    - xrayutilities.io
    - xrayutilities.materials
    - xrayutilities.math
    - xrayutilities.simpack

about:
  home: http://xrayutilities.sourceforge.net
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'package for x-ray diffraction data evaluation'
  license_family: GPL2
