{% set name = "tinydb" %}
{% set version = "3.13.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a05c4c81e6e867c4f8a2e51c5236d0d897019aa5e9296f5947455b0bdd3c519d" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
    - pytest-runner

  run:
    - python

test:
  imports:
    - tinydb

about:
  home: https://github.com/msiemens/tinydb
  license: MIT License
  license_family: MIT
  summary: TinyDB is a tiny, document oriented database optimized for your happiness :)
  doc_url: 'http://tinydb.readthedocs.io'

extra:
  recipe-maintainers: ''
