package:
    name: bitshuffle
    version: 0.4.3.0
source:
   git_url: https://github.com/kiyo-masui/bitshuffle.git
   # Commit Oct 16, 2019
   git_rev: a60471d37a8cbbd8265dc8cfa83a9320abdcb590

requirements:
    host:
        - python>=3.9*
        - numpy
        - cython
        - h5py
    run:
        - python>=3.9*
    build:
        - python
        - {{ compiler('cxx') }}
        - setuptools
        - git
        - m2-patch # [ win ]

about:
    home: https://github.com/kiyo-masui/bitshuffle/blob/master/setup.py
    summary: "bitshuffle library."
