package:
    name: bitshuffle
    version: 0.3.6.1
source:
   git_url: https://github.com/kiyo-masui/bitshuffle.git
   # Commit Oct 16, 2019
   git_rev: cc6c11216b88863f5c1958ebfd99175eea82bac7
    # path: ..
   patches:
     - setup.py.patch

requirements:
    host:
        - python
        - numpy >=1.11
        - cython
        - h5py
    run:
        - python
    build:
        - python
        - {{ compiler('cxx') }}
        - setuptools
        - git
        - patch

about:
    home: https://github.com/kiyo-masui/bitshuffle/blob/master/setup.py
    summary: "bitshuffle library."
