package:
    name: bitshuffle
    version: 0.2.4.1
source:
    git_url: https://github.com/kiyo-masui/bitshuffle.git
    git_rev: 0.2.4
    # path: ..
    patches:
      - setup.py.patch

build:
    number: 2

requirements:
    build:
        - python
        - setuptools
        - cython
        - numpy
        - h5py >=2.7.*
        - hdf5 ==1.8.20
    run:
        - python 
        - numpy
        - h5py
        - cython

about:
    home: https://github.com/kiyo-masui/bitshuffle/blob/master/setup.py
    summary: "bitshuffle library."
