name: "Build Conda Packages"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: conda build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: ["ubuntu-latest", "macos-latest"]
    env:
      MY_CONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      MY_CONDA_CHANNEL: "paulscherrerinstitute"
      MY_CONDA_CMD: "conda"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          conda-build-version: 3
          auto-activate-base: true
          activate-environment: ""
      - name: Dump environments
        run: |
            printenv
            mkdir packages
            conda info
      - name: Setup Xcode and SDK on macOS
        if: runner.os == 'macOS'
        run: |
            MACOS_SDK=MacOSX10.9.sdk
            curl -OL https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/${MACOS_SDK}.tar.xz
            sudo tar xf ${MACOS_SDK}.tar.xz -C /opt
            printf "CONDA_BUILD_SYSROOT:\n    - /opt/${MACOS_SDK}\n" >> conda_build_config.yaml
      - name: Setup docker
        if: runner.os == 'Linux'
        run: |
            ./start_docker.sh $(pwd)/packages
            echo "MY_CONDA_CMD=./conda_in_docker.sh" >> $GITHUB_ENV
      - name: Build ${{ runner.os }} Packages
        run: |
            ${MY_CONDA_CMD} install anaconda-client
            ${MY_CONDA_CMD} info
            [[ -z "$MY_CONDA_TOKEN" ]] || ${MY_CONDA_CMD} config --set anaconda_upload yes
            [[ -n "$MY_CONDA_TOKEN" ]] || MY_CONDA_TOKEN=placeholder
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing epics-base || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing lzf || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing bitshuffle || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing cachannel || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing pcaspy || true
      - name: Build pure python packages
        run: |
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing pyepics || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing bottle || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing tinydb || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing phpserialize || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing xrt || true
        if: runner.os == 'Linux'
      - name: Stop docker
        if: runner.os == 'Linux'
        run: |
            ./stop_docker.sh
